//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfi.Server.Core.Infrastructure.DataContext
{
    //using System;
    using Vfi.Server.Core.DataModel.BaseEntities;
    using System.Data.Entity;
    
    public class VfiEntities : DbContext
    {
        public VfiEntities()
            : base("name=VfiEntities")
        {
        }
    
        public DbSet<Machine> Machines { get; set; }
        public DbSet<MachineAppraisal> MachineAppraisals { get; set; }
        public DbSet<MaterialInventory> MaterialInventories { get; set; }
        public DbSet<MaterialInventoryPeriod> MaterialInventoryPeriods { get; set; }
        public DbSet<ProductInventory> ProductInventories { get; set; }
        public DbSet<ProductInventoryPeriod> ProductInventoryPeriods { get; set; }
        public DbSet<StockOrder> StockOrders { get; set; }
        public DbSet<StockOrderDetail> StockOrderDetails { get; set; }
        public DbSet<StockOrderType> StockOrderTypes { get; set; }
        public DbSet<TransactionDetail> TransactionDetails { get; set; }
        public DbSet<Warehouse> Warehouses { get; set; }
        public DbSet<WarehouseType> WarehouseTypes { get; set; }
        public DbSet<Currency> Currencies { get; set; }
        public DbSet<Material> Materials { get; set; }
        public DbSet<MaterialClassified> MaterialClassifieds { get; set; }
        public DbSet<MaterialType> MaterialTypes { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<UnitMeasure> UnitMeasures { get; set; }
        public DbSet<PriceListMaterial> PriceListMaterials { get; set; }
        public DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public DbSet<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public DbSet<ShipMethod> ShipMethods { get; set; }
        public DbSet<Vendor> Vendors { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<CustomerType> CustomerTypes { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Invoice> Invoices { get; set; }
        public DbSet<InvoiceDetail> InvoiceDetails { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<TimeLine> TimeLines { get; set; }
        public DbSet<Function> Functions { get; set; }
        public DbSet<Menu> Menus { get; set; }
        public DbSet<Parameter> Parameters { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<WorkGroup> WorkGroups { get; set; }
        public DbSet<Transaction> Transactions { get; set; }
        public DbSet<ToolDetail> ToolDetails { get; set; }
        public DbSet<ToolPeriod> ToolPeriods { get; set; }
        public DbSet<UserWorkGroup> UserWorkGroups { get; set; }
        public DbSet<Tool> Tools { get; set; }
        public DbSet<ScrapReason> ScrapReasons { get; set; }
        public DbSet<WorkOrder> WorkOrders { get; set; }
        public DbSet<WorkOrderRouting> WorkOrderRoutings { get; set; }
    }
}
