//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfi.Server.Core.DataModel.BaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forecast
    {
        // Primitive properties
    
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<double> ForecastsQuality { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
    }
}
