//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfi.Server.Core.DataModel.BaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Function
    {
        public Function()
        {
            Children = new HashSet<Function>();
            Permissions = new HashSet<Permission>();
        }
    
        // Primitive properties
    
        public int FunctionId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string FunctionCode { get; set; }
        public string FunctionName { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public Nullable<byte> IDx { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<Function> Children { get; set; }
        public virtual Function Parent { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
    
    }
}
