//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfi.Server.Core.DataModel.BaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        // Primitive properties
    
        public long InvoiceDetailId { get; set; }
        public Nullable<long> InvoiceId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ProductDespatchNoteId { get; set; }
        public Nullable<double> ProductLength { get; set; }
        public Nullable<int> Bundle { get; set; }
        public Nullable<int> Piece { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> VatAmount { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<int> RemainedBundle { get; set; }
        public Nullable<double> RemainedWeight { get; set; }
        public Nullable<int> RemainedPiece { get; set; }
        public string Note { get; set; }
        public bool Active { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        // Navigation properties
    
        public virtual Product Product { get; set; }
        public virtual Invoice Invoice { get; set; }
    
    }
}
