//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfi.Server.Core.DataModel.BaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialClassified
    {
        public MaterialClassified()
        {
            MaterialTypes = new HashSet<MaterialType>();
            PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
        }
    
        // Primitive properties
    
        public int MaterialClassifiedId { get; set; }
        public string MaterialClassifiedName { get; set; }
        public bool Active { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<MaterialType> MaterialTypes { get; set; }
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
    
    }
}
