//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfi.Server.Core.DataModel.BaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialInventory
    {
        // Primitive properties
    
        public int MaterialInventoryId { get; set; }
        public int MaterialId { get; set; }
        public int WarehouseId { get; set; }
        public Nullable<double> TotalQty { get; set; }
        public Nullable<double> TotalQtyKg { get; set; }
        public Nullable<double> AvailableQty { get; set; }
        public Nullable<double> UnavailableQty { get; set; }
        public string UnitMeasure { get; set; }
        public byte Status { get; set; }
        public bool Active { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        // Navigation properties
    
        public virtual Material Material { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    
    }
}
