//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfi.Server.Core.DataModel.BaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            MaterialInventories = new HashSet<MaterialInventory>();
            MaterialInventoryPeriods = new HashSet<MaterialInventoryPeriod>();
            StockOrderDetails = new HashSet<StockOrderDetail>();
            TransactionDetails = new HashSet<TransactionDetail>();
            PriceListMaterials = new HashSet<PriceListMaterial>();
            Products = new HashSet<Product>();
            PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
        }
    
        // Primitive properties
    
        public int MaterialId { get; set; }
        public int MaterialTypeId { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string Diameter { get; set; }
        public string DiameterType { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Weight { get; set; }
        public bool Active { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<MaterialInventory> MaterialInventories { get; set; }
        public virtual ICollection<MaterialInventoryPeriod> MaterialInventoryPeriods { get; set; }
        public virtual ICollection<StockOrderDetail> StockOrderDetails { get; set; }
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
        public virtual MaterialType MaterialType { get; set; }
        public virtual ICollection<PriceListMaterial> PriceListMaterials { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
    
    }
}
