//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfi.Server.Core.DataModel.BaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public OrderDetail()
        {
            OrderStatuses = new HashSet<OrderStatus>();
            TimeLines = new HashSet<TimeLine>();
        }
    
        // Primitive properties
    
        public long OrderDetailId { get; set; }
        public long OrderId { get; set; }
        public int ProductId { get; set; }
        public string CarrierTrackingNumber { get; set; }
        public short OrderQty { get; set; }
        public double UnitPrice { get; set; }
        public double UnitPriceDiscount { get; set; }
        public double LineTotal { get; set; }
        public bool Active { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> VFIDueDate { get; set; }
        public Nullable<System.DateTime> CustomerDueDate { get; set; }
    
        // Navigation properties
    
        public virtual Product Product { get; set; }
        public virtual ICollection<OrderStatus> OrderStatuses { get; set; }
        public virtual Order Order { get; set; }
        public virtual ICollection<TimeLine> TimeLines { get; set; }
    
    }
}
