//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfi.Server.Core.DataModel.BaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatus
    {
        // Primitive properties
    
        public int OrderStatusId { get; set; }
        public Nullable<long> OrderDetailId { get; set; }
        public Nullable<double> Qty { get; set; }
        public byte Status { get; set; }
    
        // Navigation properties
    
        public virtual OrderDetail OrderDetail { get; set; }
    
    }
}
