//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfi.Server.Core.DataModel.BaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            WorkOrders = new HashSet<WorkOrder>();
            OrderDetails = new HashSet<OrderDetail>();
            Orders1 = new HashSet<Order>();
        }
    
        // Primitive properties
    
        public long OrderId { get; set; }
        public Nullable<long> ParentOrderId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> SalesPersonId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public byte Status { get; set; }
        public string OrderNumber { get; set; }
        public string PoNumber { get; set; }
        public string LotNumber { get; set; }
        public string ModelNumber { get; set; }
        public string BillToAddress { get; set; }
        public string ShipToAddress { get; set; }
        public Nullable<int> ShipMethodId { get; set; }
        public Nullable<byte> ShipmentDay { get; set; }
        public string Note { get; set; }
        public string CurrencyCode { get; set; }
        public bool Active { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<WorkOrder> WorkOrders { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<Order> Orders1 { get; set; }
        public virtual Order Order1 { get; set; }
    
    }
}
