//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfi.Server.Core.DataModel.BaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        // Primitive properties
    
        public int PermissionId { get; set; }
        public Nullable<bool> Creation { get; set; }
        public Nullable<bool> Modification { get; set; }
        public Nullable<bool> Deletion { get; set; }
        public Nullable<bool> Execution { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> WorkGroupID { get; set; }
        public string Description { get; set; }
        public Nullable<int> FunctionID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        // Navigation properties
    
        public virtual Function Function { get; set; }
        public virtual User User { get; set; }
        public virtual WorkGroup WorkGroup { get; set; }
    
    }
}
