//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfi.Server.Core.DataModel.BaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceListMaterial
    {
        // Primitive properties
    
        public long PriceListMaterialId { get; set; }
        public int MaterialId { get; set; }
        public Nullable<double> NetPrice { get; set; }
        public string Currency { get; set; }
        public Nullable<double> Exchange { get; set; }
        public bool Active { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        // Navigation properties
    
        public virtual Currency Currency1 { get; set; }
        public virtual Material Material { get; set; }
    
    }
}
