//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfi.Server.Core.DataModel.BaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            MachineAppraisals = new HashSet<MachineAppraisal>();
            ProductInventories = new HashSet<ProductInventory>();
            ProductInventoryPeriods = new HashSet<ProductInventoryPeriod>();
            StockOrderDetails = new HashSet<StockOrderDetail>();
            TransactionDetails = new HashSet<TransactionDetail>();
            InvoiceDetails = new HashSet<InvoiceDetail>();
            OrderDetails = new HashSet<OrderDetail>();
        }
    
        // Primitive properties
    
        public int ProductId { get; set; }
        public int CustomerId { get; set; }
        public int MaterialId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string DesignNo { get; set; }
        public Nullable<double> Diameter { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Weight { get; set; }
        public bool Active { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<double> ForecastsQuality { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<MachineAppraisal> MachineAppraisals { get; set; }
        public virtual ICollection<ProductInventory> ProductInventories { get; set; }
        public virtual ICollection<ProductInventoryPeriod> ProductInventoryPeriods { get; set; }
        public virtual ICollection<StockOrderDetail> StockOrderDetails { get; set; }
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
        public virtual Material Material { get; set; }
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    
    }
}
