//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfi.Server.Core.DataModel.BaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInventoryPeriod
    {
        // Primitive properties
    
        public long ProductInventoryPeriodId { get; set; }
        public long TransactionId { get; set; }
        public int WarehouseId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> PeriodDay { get; set; }
        public Nullable<int> PeriodMonth { get; set; }
        public Nullable<int> PeriodYear { get; set; }
        public Nullable<System.DateTime> PeriodDate { get; set; }
        public Nullable<double> EarlyPeriodQuantity { get; set; }
        public Nullable<double> EarlyPeriodPrice { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> Price { get; set; }
        public string UnitMeasure { get; set; }
        public Nullable<double> LastPeriodQuantity { get; set; }
        public Nullable<double> LastPeriodPrice { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        // Navigation properties
    
        public virtual Product Product { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual Transaction Transaction { get; set; }
    
    }
}
