//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfi.Server.Core.DataModel.BaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipMethod
    {
        public ShipMethod()
        {
            PurchaseOrders = new HashSet<PurchaseOrder>();
        }
    
        // Primitive properties
    
        public int ShipMethodId { get; set; }
        public string Name { get; set; }
        public Nullable<double> ShipBase { get; set; }
        public Nullable<double> ShipRate { get; set; }
        public bool Active { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
    
    }
}
