//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfi.Server.Core.DataModel.BaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOrderDetail
    {
        // Primitive properties
    
        public long StockOrderDetailId { get; set; }
        public long StockOrderId { get; set; }
        public Nullable<int> ReferenceId { get; set; }
        public bool MoP { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string UnitMeasure { get; set; }
        public bool Active { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        // Navigation properties
    
        public virtual StockOrder StockOrder { get; set; }
        public virtual Material Material { get; set; }
        public virtual Product Product { get; set; }
    
    }
}
