//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfi.Server.Core.DataModel.BaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOrder
    {
        public StockOrder()
        {
            StockOrderDetails = new HashSet<StockOrderDetail>();
            Transactions = new HashSet<Transaction>();
        }
    
        // Primitive properties
    
        public long StockOrderId { get; set; }
        public Nullable<int> WarehouseIssueId { get; set; }
        public Nullable<int> WarehouseReceiptId { get; set; }
        public int StockOrderTypeId { get; set; }
        public string StockOrderCode { get; set; }
        public string EoI { get; set; }
        public bool MoP { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public byte Status { get; set; }
        public bool IsApprove { get; set; }
        public bool Active { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        // Navigation properties
    
        public virtual Warehouse WarehouseIssue { get; set; }
        public virtual Warehouse WarehouseReceipt { get; set; }
        public virtual ICollection<StockOrderDetail> StockOrderDetails { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    
    }
}
