//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfi.Server.Core.DataModel.BaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeLine
    {
        // Primitive properties
    
        public int TimeLineId { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<int> Times { get; set; }
        public Nullable<int> RealTimes { get; set; }
        public Nullable<double> Performance { get; set; }
        public Nullable<System.DateTime> StartDay { get; set; }
        public Nullable<System.DateTime> FinishedDay { get; set; }
        public Nullable<int> WorkingHours { get; set; }
        public bool Active { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> OrderDetailId { get; set; }
    
        // Navigation properties
    
        public virtual Warehouse Warehouse { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
    
    }
}
