//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfi.Server.Core.DataModel.BaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolDetail
    {
        // Primitive properties
    
        public int ToolDetailId { get; set; }
        public int ToolId { get; set; }
        public double Quantity { get; set; }
        public bool Active { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ToolOrderId { get; set; }
    
        // Navigation properties
    
        public virtual Tool Tool { get; set; }
        public virtual ToolOrder ToolOrder { get; set; }
    
    }
}
