//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfi.Server.Core.DataModel.BaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolOrder
    {
        public ToolOrder()
        {
            ToolDetails = new HashSet<ToolDetail>();
        }
    
        // Primitive properties
    
        public int ToolOrderId { get; set; }
        public string TransactionCode { get; set; }
        public string EoI { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public byte Status { get; set; }
        public bool IsApprove { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<ToolDetail> ToolDetails { get; set; }
    
    }
}
