//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfi.Server.Core.DataModel.BaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolPeriod
    {
        // Primitive properties
    
        public long ToolPeriodId { get; set; }
        public int ToolId { get; set; }
        public Nullable<int> PeriodDay { get; set; }
        public Nullable<int> PeriodMonth { get; set; }
        public Nullable<int> PeriodYear { get; set; }
        public Nullable<System.DateTime> PeriodDate { get; set; }
        public Nullable<double> EarlyPeriodQuantity { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> LastPeriodQuantity { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        // Navigation properties
    
        public virtual Tool Tool { get; set; }
    
    }
}
