//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfi.Server.Core.DataModel.BaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tool
    {
        public Tool()
        {
            ToolDetails = new HashSet<ToolDetail>();
            ToolPeriods = new HashSet<ToolPeriod>();
        }
    
        // Primitive properties
    
        public int ToolId { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ToolName { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<ToolDetail> ToolDetails { get; set; }
        public virtual ICollection<ToolPeriod> ToolPeriods { get; set; }
    
    }
}
