//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfi.Server.Core.DataModel.BaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public Warehouse()
        {
            MachineAppraisals = new HashSet<MachineAppraisal>();
            MaterialInventories = new HashSet<MaterialInventory>();
            MaterialInventoryPeriods = new HashSet<MaterialInventoryPeriod>();
            ProductInventories = new HashSet<ProductInventory>();
            ProductInventoryPeriods = new HashSet<ProductInventoryPeriod>();
            StockOrders = new HashSet<StockOrder>();
            StockOrders1 = new HashSet<StockOrder>();
            TimeLines = new HashSet<TimeLine>();
            Transactions = new HashSet<Transaction>();
            Transactions1 = new HashSet<Transaction>();
        }
    
        // Primitive properties
    
        public int WarehouseId { get; set; }
        public Nullable<int> WarehouseTypeId { get; set; }
        public string WarehouseName { get; set; }
        public string Description { get; set; }
        public int Idx { get; set; }
        public bool DisplayInReport { get; set; }
        public bool Active { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<MachineAppraisal> MachineAppraisals { get; set; }
        public virtual ICollection<MaterialInventory> MaterialInventories { get; set; }
        public virtual ICollection<MaterialInventoryPeriod> MaterialInventoryPeriods { get; set; }
        public virtual ICollection<ProductInventory> ProductInventories { get; set; }
        public virtual ICollection<ProductInventoryPeriod> ProductInventoryPeriods { get; set; }
        public virtual ICollection<StockOrder> StockOrders { get; set; }
        public virtual ICollection<StockOrder> StockOrders1 { get; set; }
        public virtual ICollection<TimeLine> TimeLines { get; set; }
        public virtual WarehouseType WarehouseType { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<Transaction> Transactions1 { get; set; }
    
    }
}
