//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfi.Server.Core.DataModel.BaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderRouting
    {
        // Primitive properties
    
        public int RoutingId { get; set; }
        public int WorkOrderId { get; set; }
        public int ProductId { get; set; }
        public int WarehouseId { get; set; }
        public System.DateTime ScheduledStartDate { get; set; }
        public System.DateTime ScheduledEndDate { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<decimal> ActualResourceHrs { get; set; }
        public Nullable<decimal> PlannedCost { get; set; }
        public Nullable<decimal> ActualCost { get; set; }
        public bool Active { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        // Navigation properties
    
        public virtual WorkOrder WorkOrder { get; set; }
    
    }
}
